import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

//conponents
import Navbar from "./componenst/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-10 lg:mx-96 md:mz-60">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
